#!/bin/sh
# Script for updating everything.
# Does a system rebuild, a home manager rebuild, flatpak update and garbage collects the nix store
# without removing direnv artifacts.
# Also does a nix-store --optimize.

if ! ([ "$1" = "push" ] || [ "$1" = "pull" ]);
    then echo "argument 1: wether to push/pull, is needed"; exit 1;
fi
if ! ([ "$2" = "light" ] || [ "$2" = "dark" ] || [ "$2" = "home" ]);
    then echo "argument 2: variation light/dark/home, is needed"; exit 1;
fi

cd ~/Projects/nixos-config \
&& git pull \
&& if [ "$1" = "push" ]; then nix flake update; fi \
&& nh home switch -c $USER@$HOSTNAME-$2 . \
&& flatpak update -y \
&& nh os switch . \
&& if [ "$1" = "push" ]; then {
     git add flake.lock \
     && git commit -m 'flake update' \
     && git push
   } fi \
&& nh clean all --k 3 --K 14d \
&& nix-store --optimize

